package com.ai.agentic.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "AI-generated answer with the SQL that was executed")
public record ChatResponse(

    @Schema(description = "Natural-language answer generated by the AI")
    String response,

    @Schema(description = "The SQL SELECT query that was auto-generated and executed")
    String generatedSql,

    @Schema(description = "Number of rows returned by the query")
    int rowsFound
) {
}
